deepgram:
  model: nova-2

openai:
  model: o1-mini

groq:
  temperature: 0
  model: distil-whisper-large-v3-en

stt:
  primary_engine: "deepgram"

# TODO
emotion:
  detection_enabled: true
  intensity_threshold: 0.6

sounds:
  min_gap_duration: 1.5 
  context_lines: 4
